name: Make Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag Name'
        default: 'v0.0.1'
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - run: bash ./scripts/pack.sh
    - name: Create Github Release
      run: gh release create "${{inputs.tag}}" -d --discussion-category "Announcement" -t "${{inputs.tag}}" out/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
